modLoader = "javafml"
loaderVersion = "[39,)"
#updateJSONURL=""
issueTrackerURL = "https://github.com/AppliedEnergistics/Applied-Mekanistics/issues"
displayURL = "https://github.com/AppliedEnergistics/Applied-Mekanistics#readme"
logoFile = "logo.png"
#credits="Thanks for this example mod goes to Java"
authors = "ramidzkh"
license = "See GitHub repository for details"

[[mods]]
modId = "appmek"
version = "${version}"
displayName = "Applied Mekanistics"
description = "Use Mekanism resources through your ME network"

[[dependencies.appmek]]
modId = "forge"
mandatory = true
versionRange = "[40.0.0,41.0.0)"
ordering = "NONE"
side = "BOTH"

[[dependencies.appmek]]
modId = "ae2"
mandatory = true
versionRange = "(,12.0.0)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.appmek]]
modId = "mekanism"
mandatory = true
versionRange = "[10.1.2,11.0.0)"
ordering = "AFTER"
side = "BOTH"
